//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EngLangD.rc
//
#define IDD_apply_angle                 3
#define IDD_apply_gauss                 3
#define IDD_gamma_aply                  3
#define IDD_apply_incline               5
#define IDD_DOTLINES_VIEW               22
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_RULER                       128
#define IDR_DIGITTYPE                   129
#define IDR_IMAGEFRAME                  129
#define IDR_IMAGETYPE                   129
#define IDR_IMAGETOOLS                  129
#define IDD_FILESPECIAL                 130
#define IDC_ZOOMIN                      130
#define IDC_ZOOMOUT                     131
#define IDD_BRIGHT_CONTRAST_DLG         132
#define IDR_TEXT_WINDOW                 132
#define IDC_ZOOMRECT                    132
#define IDD_ZOOM_DLG                    133
#define IDD_GAUSS_DLG                   135
#define IDD_RATIO_DLG                   136
#define IDC_ZOOMRECTDRAG                137
#define IDD_ROTATION_DLG                138
#define IDD_MEASURE_DLG                 140
#define IDD_INCLINE_CORRECT_DLG         154
#define IDD_GAMMA_CORRECTION_DLG        156
#define IDR_DIGITTOOLS                  159
#define IDD_BOUNDS_DLG                  163
#define IDD_CROP_DLG                    165
#define IDB_BITMAP1                     167
#define IDB_BITMAP2                     168
#define IDB_BITMAP3                     169
#define IDB_BITMAP4                     170
#define IDB_BITMAP5                     171
#define IDB_BITMAP6                     172
#define IDB_BITMAP7                     173
#define IDB_BITMAP8                     174
#define IDB_BITMAP9                     175
#define IDB_BITMAP10                    176
#define IDB_BITMAP11                    177
#define IDB_BITMAP12                    178
#define IDB_BITMAP13                    179
#define IDB_BITMAP14                    180
#define IDB_BITMAP15                    181
#define IDB_BITMAP16                    182
#define IDD_TOOLBARS_DLG                184
#define IDR_KITTOOL                     185
#define IDR_IMAGEINFO                   185
#define IDD_ABOUTBOX1                   186
#define IDR_BOUND_MENU                  187
#define IDC_RECT_BOUND_CUR              189
#define IDR_VIEW                        195
#define IDR_VIEWTOOLS                   195
#define IDC_SEL_ZAP_SEC                 197
#define IDC_SEL_DOT                     198
#define IDR_EDITTOOLS                   199
#define IDB_BITMAP17                    200
#define IDD_APPROXSET_DLG               201
#define IDC_SEL_PT_CURSOR               210
#define IDC_SEL_SEC_CURSOR              221
#define IDC_MEASURE_CUR                 226
#define IDC_MARK_BOUND_CUR              234
#define IDC_SEL_SEC_CURSOR1             235
#define IDS_brightness                  1000
#define IDC_DELETE                      1000
#define IDE_brightness                  1001
#define IDS_contrast                    1002
#define IDE_slur                        1002
#define IDE_contrast                    1003
#define IDE_angle_rot                   1003
#define IDS_zoom_scale                  1004
#define IDB_clear_measure               1005
#define IDR_cw_rot                      1008
#define IDR_ccw_rot                     1009
#define IDE_Threshold                   1010
#define IDB_apert_load                  1011
#define IDB_apert_add                   1012
#define IDB_apert_clear                 1013
#define IDB_obstruct_load               1014
#define IDB_obstruct_add                1015
#define IDB_obstruct_clear              1016
#define IDE_gamma                       1018
#define IDS_slur                        1019
#define IDS_gamma                       1020
#define IDCB_bound_type                 1021
#define IDD_apply_crop                  1023
#define IDCB_Toolbar_list               1024
#define IDE_comments_info               1025
#define IDE_scalefactor                 1026
#define IDE_rotation                    1027
#define IDC_SPIN2                       1030
#define IDE_FringeNum                   1031
#define IDE_FringeNumCtrl               1033
#define IDCB_FringeAs                   1034
#define IDE_approx_pow                  1035
#define IDE_approx_dist                 1036
#define IDCB_zoom_scale                 1038
#define IDCB_obstruct_type              1050
#define IDCB_apert_type                 1051
#define IDT_X_val_rot                   1065
#define IDT_Y_val_rot                   1066
#define IDT_H_val_rot                   1067
#define IDT_W_val_rot                   1068
#define IDT_A_val_rot                   1069
#define IDT_D_val_rot                   1070
#define IDCB_HW_resize_ms               1072
#define IDCB_proc_resize_ms             1076
#define IDT_X_measure                   1080
#define IDT_Y_measure                   1081
#define IDT_H_measure                   1082
#define IDT_W_measure                   1083
#define IDT_A_measure                   1084
#define IDT_D_measure                   1085
#define stc32                           0x045f
#define IDBM_PREOPEN_PICTURE            1124
#define IDD_FILE_OPEN                   32771
#define IDD_FILE_SAVE_AS                32772
#define IDD_UNDO                        32773
#define IDD_ZOOM_IMAGE                  32774
#define IDD_CONTRAST_BRIGHTNESS         32775
#define IDD_ROTATION_IMAGE              32776
#define IDD_GAUSS_IMAGE                 32777
#define IDD_RATIO_IMAGE                 32778
#define IDD_INVERTION_IMAGE             32779
#define IDD_ROTATION_180                32780
#define IDD_ROTATION_90_CLOCKWISE       32781
#define IDD_ROTATION_90_ANTICLOCKWISE   32782
#define IDD_ROTATION_CUSTOM             32783
#define IDD_ROTATION_HORZ               32784
#define IDD_ROTATION_VERT               32786
#define IDD_MEASURE                     32787
#define IDD_FOTO_SECTIONS               32788
#define IDD_SH_SECTIONS                 32789
#define ID_MENUITEM32790                32790
#define IDD_SH_DOTS                     32791
#define IDD_SH_IMAGE                    32792
#define IDD_SH_DRAFT                    32793
#define IDD_INTR_ANALYSIS               32794
#define IDD_DIFRA_ANALYSIS              32795
#define IDD_CALCULATOR                  32796
#define IDD_INTERF_PROP                 32797
#define IDD_DIFRA_PROP                  32798
#define IDD_VIEW_IMAGETOOLS             32802
#define IDD_INCLINE_IMAGE               32805
#define IDD_GAMMA_IMAGE                 32806
#define IDD_AVTO_D                      32807
#define IDD_SECTION_D                   32808
#define IDD_AUTO_D                      32809
#define IDD_FRINGES_D                   32810
#define IDD_CLEAR_D                     32810
#define IDD_CROP_IMAGE                  32811
#define IDD_EXPAND_IMAGE                32812
#define IDD_AUTOCONTRAST_IMAGE          32813
#define IDD_CHANGE_LANG                 32814
#define IDD_HELP                        32815
#define IDD_E_SEC_D                     32817
#define IDD_E_FR_D                      32818
#define IDD_ADD_DOT_D                   32819
#define IDD_DEL_DOT_D                   32820
#define IDD_RENUM_DOT_D                 32821
#define IDD_RENUM_FR_D                  32822
#define IDD_NUMBER_D                    32823
#define IDD_DEL_FR_D                    32824
#define IDD_ADD_SEC_D                   32825
#define IDD_DEL_SEC_D                   32826
#define IDD_SEC_LEFT_D                  32827
#define IDD_SEC_RIGHT_D                 32828
#define IDD_TOOLBARS                    32829
#define IDD_INTR_ANALYSIS_OPTIONS       32830
#define IDD_DIFRA_ANALYSIS_CONTRL       32831
#define IDD_INTR_ANALYSIS_CONTROL       32832
#define IDD_IMAGE_GENERATION            32833
#define IDD_INFO_TEXT_WND               32834
#define IDD_COPY                        32835
#define IDD_CLONE                       32836
#define IDD_BOUND_APPLY                 32841
#define IDD_BOUND_LASTREMOVE            32842
#define IDD_BOUND_ALLREMOVE             32843
#define IDD_COPY_SCENARIO               32844
#define IDD_PAST_SCENARIO               32845
#define IDD_BOUND_SETDOTS               32846
#define IDD_PASTE_SCENARIO              32847
#define IDD_BOUND_SETRECT               32848
#define IDD_BOUND_SCRROUND              32849
#define IDD_BOUND_SCRELLIPSE            32850
#define IDD_BOUND_SCRRECT               32851
#define IDD_BOUND_SCRPLG                32852
#define IDD_OPEN_SCENARIO               32853
#define IDD_SAVE_SCENARIO               32854
#define IDD_NUM_OFF_MINUS               32855
#define IDD_NUM_OFF_PLUS                32856
#define IDD_ZOOM_IN                     32857
#define IDD_ZOOM_OUT                    32858
#define IDD_ZOOM_FIT                    32859
#define IDD_FC_MAX                      32860
#define IDD_FC_MIN                      32861
#define IDD_FC_MINMAX                   32862
#define ID_NUMBERING                    32863
#define IDD_INTERFEROGRAM_VIEW          32863
#define ID_IMAGE                        32864
#define IDD_EXTRFRINGE_VIEW             32864
#define IDD_DOTS_VIEW                   32865
#define IDD_SECTIONS_VIEW               32867
#define IDD_APPROX_VIEW                 32868
#define IDD_BOUNDS_EXT                  32869
#define IDD_BOUNDS_INS                  32870
#define IDD_BOUND_CURREMOVE             32871
#define IDD_INTERFEROGRAM_INFO          32872
#define IDD_DIGIT_PARAMETERS            32873
#define IDD_ADV_PARAMETERS              32874
#define IDD_CALC_APROX                  32875
#define ID_FRINGE_NUM                   59395
#define ID_FRINGE_NUM_CTRL              59396
#define IDW_EDIT                        59397

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32876
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
